### ISSUE TITLE
README links to outdated documentation

### ISSUE THREAD

**Issue by epage** [mikedilger/float-cmp#15]
README linked to this: https://mikedilger.github.io/float-cmp/float_cmp/index.html
Same with [Cargo.toml](https://github.com/mikedilger/float-cmp/blob/master/Cargo.toml#L7)

Not sure what version that is for.

This link instead takes me to the latest: https://docs.rs/float-cmp/

**Comment by mikedilger** [comment]
Thanks, fixed.
