### ISSUE TITLE
Consider removing the num-traits dependency 

### ISSUE THREAD

**Issue by RazrFalcon** [mikedilger/float-cmp#16]
`num-traits` hurts build time quite a lot.

With `num-traits`:

```
> hyperfine 'cargo clean; cargo build --release'
  Time (mean ± σ):      2.840 s ±  0.157 s    [User: 3.609 s, System: 0.170 s]
  Range (min … max):    2.766 s …  3.280 s    10 runs
```

Without (I had to comment out the `ApproxEqRatio` trait):

```
> hyperfine 'cargo clean; cargo build --release'
  Time (mean ± σ):     271.0 ms ±   1.7 ms    [User: 280.1 ms, System: 47.1 ms]
  Range (min … max):   269.1 ms … 273.6 ms    10 runs
```

According to this benchmarks, `num-traits` makes compilation ~13 times slower.

Do we really need `num-traits`? And if so, can we make them optional?

Personally, I need only `ApproxEqUlps`.

**Comment by mikedilger** [comment]
I didn't realize it was that significant.

I've pushed a commit making 'num-traits' optional, but on by default.  ApproxEqRatio is not available if num-traits is not enabled, since I didn't think up a clever way to code it without Zero.

Let me know if it works for you and I'll cut a new version.

**Comment by RazrFalcon** [comment]
Thanks! Now it builds faster.

**Comment by RazrFalcon** [comment]
Version bump?

**Comment by mikedilger** [comment]
Yep, sorry. Done.

**Comment by RazrFalcon** [comment]
Thanks!

**Comment by mikedilger** [comment]
I had to yank 0.4.1 because I didn't realize I had a lot of breaking changes on master.  I've republished as 0.5.

**Comment by RazrFalcon** [comment]
Yeah, that's explains why my CI was broken yesterday. Will update to a newer version.
