### ISSUE TITLE
Breaking change introduced in 0.4.0 -> 0.4.1

### ISSUE THREAD

**Issue by 0x-r4bbit** [mikedilger/float-cmp#17]
https://github.com/mikedilger/float-cmp/commit/d93fe51aa928cfdb269af67331846d533e850ec4 introduced a breaking change a long time ago, however it has just been released only a day ago. 

Other libraries such as https://github.com/assert-rs/predicates-rs depend on float-cmp and due to this breaking change, all my tests are failing:

```
error[E0061]: this function takes 2 parameters but 3 parameters were supplied
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/predicates-1.0.1/src/float/close.rs:86:18
   |
86 |         variable.approx_eq(&self.target, self.epsilon, self.ulps)
   |                  ^^^^^^^^^ expected 2 parameters
```

Not sure what's the best way forward from here... deprecated 0.4.1 and release 1.0.0? Patch predicates (1.0.2) or follow semver and go 2.0.0 with the upgrade?

**Comment by mikedilger** [comment]
Ouch.  I'm sorry.  I can't believe I missed that I must be sleeping.
I've yanked 0.4.1 and republished the breaking change version as 0.5.0.

**Comment by epage** [comment]
This does give me the idea that cargo-release could error check this for you.  See https://github.com/sunng87/cargo-release/issues/62

**Comment by 0x-r4bbit** [comment]
Thanks @mikedilger for taking care of this so quickly!
