### ISSUE TITLE
approx_eq! macro requires additional imports

### ISSUE THREAD

**Issue by ebkalderon** [mikedilger/float-cmp#18]
Because the `approx_eq!` macro does not refer to the `ApproxEq` trait using `$crate::ApproxEq` internally, users must also bring this trait into scope themselves, which breaks the convenient abstraction the macro is trying to provide.

**Comment by mikedilger** [comment]
thanks

**Comment by ebkalderon** [comment]
@mikedilger Thank you for the very quick response!
