### ISSUE TITLE
Add assert_approx_eq macro

### ISSUE THREAD

**Issue by robinkrahl** [mikedilger/float-cmp#27]
When using the `assert!(approx_eq!( ... ))` construction in unit tests, the output if the assertion fails is not very instructive.  Therefore I use the following macro in my tests which produces output similar to `assert_eq`:

```rust
    macro_rules! assert_approx_eq {
        ($typ:ty, $lhs:expr, $rhs:expr) => {
            let left = $lhs;
            let right = $rhs;
            assert!(
                approx_eq!($typ, left, right),
                "assertion failed: `(left approx_eq right)`
  left: `{:?}`,
 right: `{:?}`", left, right
            );
        };
    }
```

Would you be interested in adding something like this to float-cmp itself?

**Comment by mikedilger** [comment]
Sure. If you want to create a PR I'll look at it.

What about putting the values of left and right into the parenthetical itself?

**Comment by robinkrahl** [comment]
> Sure. If you want to create a PR I'll look at it.

Okay, I’ll prepare a PR!

> What about putting the values of left and right into the parenthetical itself?

This would work for float comparisons, but for example in my use case, I’m comparing structs that implement `ApproxEq` and that would be very hard to read if printed inline.  Also, I tried to mimic the message used by `assert_eq`, see [`std::panicking::assert_failed_inner`](https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/panicking.rs#L141).
