### ISSUE TITLE
Incorrect behavior when crossing positive/negative boundary

### ISSUE THREAD

**Issue by mwlon** [mikedilger/float-cmp#33]
The floats `0.0` and `-0.0` should be 1 ULP apart, but this crate currently gives -2147483648:

```rust
use float_cmp::Ulps;

fn main() {
  println!("{}", 0.0_f32.ulps(&-0.0));
}

>> -2147483648
```

Here's an example of what a correct (and still branch-free and fast, but maybe not as fast) order-preserving conversion from float->int would look like: https://github.com/mwlon/pcodec/blob/0f91bef292b9a7422afe0d83b7b23efe577c6731/pco/src/data_types/floats.rs#L84

**Comment by mikedilger** [comment]
Yeah, I'm kinda shocked it was like this for so long.  Fixed in 6a9facf22355bb9deabf5dfe7ff8ed379e67394a
