### ISSUE TITLE
Remove the 'num' crate dependancy

### ISSUE THREAD

**Issue by RazrFalcon** [mikedilger/float-cmp#6]
As far as I understand the 'num' crate used only here: https://github.com/mikedilger/float-cmp/blob/master/src/lib.rs#L430

Isn't it easier to reimplement `Zero` trait to get rid of [big](https://crates.io/crates/num) `num` dependency? Or you can use only the `num-traits` crate.

**Comment by mikedilger** [comment]
Sounds like a good idea.   I'll take a look once crates.io stops acting up.

**Comment by mikedilger** [comment]
done.
